# Generated by Django 3.2.8 on 2021-10-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=100)),
                ('actor', models.CharField(max_length=500)),
                ('plot', models.CharField(max_length=2000)),
                ('image_link', models.URLField(max_length=2000)),
                ('IMDB_link', models.URLField(max_length=2000)),
            ],
        ),
    ]
